name: finance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.4
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - mysql-connector-python=8.2.0
  - tk=8.6.12
  - jupyter
  - pip
  - pip:
    - configparser==6.0.0
    - python-dateutil>=2.8.2
    - pytz>=2023.3
    - tzdata>=2023.3